version: "3.9"
services:
  redis:
    image: redis
    container_name: redis1
    restart: always
    ports:
      - "6379:6379"
    command: >
      --bind 0.0.0.0
  redis-commander:
    # http://localhost:8081
    image: rediscommander/redis-commander:latest
    container_name: rediscommander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - "8081:8081"
    depends_on:
      - redis
